version: "3"
services:
  eam:
    build: .
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    image: "docker_eam:latest"
    network_mode: "host"
    runtime: nvidia
    environment:
      - IP_KAFKA=intrepid01.diginext.fr
      - PORT_KAFKA=9092
      - SERVER_IPS=192.168.100.30
      - SERVER_PORTS=23098
      - NVIDIA_VISIBLE_DEVICES=all
      - DISPLAY=$DISPLAY
      - NVIDIA_DRIVER_CAPABILITIES=all
      - DISPLAY = $DISPLAY
    command: bash -c "
      python3 -u object_detections_EAM.py
      "
