version: "3"
services:
  eam:
    build: .
    ports:
      - "3939:3939"
      - "4567:4567"
    image: "docker_eam:latest"
    runtime: nvidia
    environment:
      - IP_KAFKA=${IP_KAFKA}
      - PORT_KAFKA=${PORT_KAFKA}
      - IP_EAM=${IP_EAM}
      - PORT_EAM=${PORT_EAM}
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
    command: bash -c "
      python3 -u object_detections_EAM.py
      "
