version: "3"
services:
  eam:
    build: .
    ports:
      - "4567:4567"
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    image: "docker_eam:latest"
    runtime: nvidia
    environment:
      - IP_KAFKA=195.251.117.126
      - PORT_KAFKA=9091
      - SERVER_IPS=192.168.43.47
      - SERVER_PORTS=4567
      - NVIDIA_VISIBLE_DEVICES=all
      - DISPLAY=$DISPLAY
      - NVIDIA_DRIVER_CAPABILITIES=all
    command: bash -c "
      python3 -u object_detections_EAM.py
      "
